CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  businessEmail VARCHAR(255) UNIQUE NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(20),
  message TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
